locale: zh-CN
title: 一安博客
email: mya12321@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  一安的个人博客， 介绍一些java， javascript， web开发相关技术
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mya12321.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author details for the jekyll-seo-tag gem
author:
  name: 一安
  email: mya12321@gmail.com
  github: mya12321

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
